[package]
name = "senses"
version = "0.0.1"
authors = ["Staneesh <blkreasons@outlook.com>"]
edition = "2018"

[dependencies]
sdl2 = "0.34.0"
gl = { path = "lib/gl" }

[features]
gl_debug = ["gl/debug"]
